services:
  webapp:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/todoApplication

  mongo:
    image: mongo
    ports:
      - "27017:27017"
