apiVersion: apps/v1
kind: Deployment
metadata:
  name: f2p-backend
  labels:
    app: f2p-backend
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: f2p-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  template:
    metadata:
      labels:
        app: f2p-backend
    spec:
      containers:
        - name: f2p-backend
          image: IMAGE_URI  # <-- this will be replaced with the actual image URL
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/todoApplication" 
          resources:
            requests:
              cpu: "150m"
              memory: "300Mi"
            limits:
              cpu: "1000m"
              memory: "2500Mi"
          startupProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
