apiVersion: v1
kind: Service
metadata:
  name: f2p-backend
  labels:
    app: f2p-backend
spec:
  type: LoadBalancer
  selector:
    app: f2p-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
